Name:           ros-jade-pyros-msgs
Version:        0.1.1
Release:        1%{?dist}
Summary:        ROS pyros_msgs package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/rocon_tools
Source0:        %{name}-%{version}.tar.gz

Requires:       python-pytest >= 2.5.1
Requires:       python-six >= 1.5.2
Requires:       ros-jade-hypothesis >= 3.0.1
Requires:       ros-jade-marshmallow >= 2.9.1
Requires:       ros-jade-message-runtime >= 0.4.12
Requires:       ros-jade-pyros-utils >= 0.1.3
Requires:       ros-jade-rospy >= 1.11.19
Requires:       ros-jade-std-msgs >= 0.5.9
BuildRequires:  python-pytest >= 2.5.1
BuildRequires:  python-six >= 1.5.2
BuildRequires:  ros-jade-catkin >= 0.6.18
BuildRequires:  ros-jade-catkin-pip >= 0.2.0
BuildRequires:  ros-jade-hypothesis >= 3.0.1
BuildRequires:  ros-jade-marshmallow >= 2.9.1
BuildRequires:  ros-jade-message-generation >= 0.2.10
BuildRequires:  ros-jade-pyros-test >= 0.0.6
BuildRequires:  ros-jade-pyros-utils >= 0.1.3
BuildRequires:  ros-jade-roslint >= 0.10.0
BuildRequires:  ros-jade-rospy >= 1.11.19
BuildRequires:  ros-jade-std-msgs >= 0.5.9

%description
Pyros messages and services definition

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Wed May 31 2017 AlexV <alexandre.vincent@yujinrobot.com> - 0.1.1-1
- Autogenerated by Bloom

* Tue May 16 2017 AlexV <alexandre.vincent@yujinrobot.com> - 0.1.1-0
- Autogenerated by Bloom

